import React, { useState } from "react";
import {
    FileText,
    FileSpreadsheet,
    Download,
    BarChart3,
    CalendarDays,
    CheckCircle,
    Loader2
} from "lucide-react";

import {
    downloadAppointmentPdf,
    downloadAppointmentExcel
} from "../services/reportService";


/**
 * ============================================================
 * AfyaSmart - Admin Reports
 * ============================================================
 *
 * This page provides administrators with access to system
 * reports generated by the AfyaSmart backend.
 *
 * Current report:
 *
 * - Appointment Report
 *
 * Available formats:
 *
 * - PDF
 * - Excel
 *
 * ============================================================
 */


/**
 * Helper function responsible for triggering a browser
 * download from a Blob returned by the backend.
 */
const saveBlobAsFile = (blob, filename) => {

    // Create a temporary URL pointing to the generated file.
    const url = window.URL.createObjectURL(blob);

    // Create an invisible download link.
    const link = document.createElement("a");

    link.href = url;
    link.download = filename;

    // Add the link temporarily to the document.
    document.body.appendChild(link);

    // Trigger the browser download.
    link.click();

    // Remove the temporary link.
    document.body.removeChild(link);

    // Release the temporary object URL.
    window.URL.revokeObjectURL(url);
};


const AdminReports = () => {

    /**
     * Tracks which report is currently being generated.
     *
     * Possible values:
     *
     * "pdf"
     * "excel"
     * null
     */
    const [downloading, setDownloading] = useState(null);


    /**
     * Stores an error message if report generation fails.
     */
    const [error, setError] = useState("");


    /**
     * ========================================================
     * Download PDF
     * ========================================================
     */
    const handleDownloadPdf = async () => {

        try {

            setError("");
            setDownloading("pdf");

            const blob =
                await downloadAppointmentPdf();

            saveBlobAsFile(
                blob,
                "AfyaSmart_Appointments_Report.pdf"
            );

        } catch (err) {

            console.error(
                "PDF report download failed:",
                err
            );

            setError(
                "Unable to generate the PDF report. Please try again."
            );

        } finally {

            setDownloading(null);
        }
    };


    /**
     * ========================================================
     * Download Excel
     * ========================================================
     */
    const handleDownloadExcel = async () => {

        try {

            setError("");
            setDownloading("excel");

            const blob =
                await downloadAppointmentExcel();

            saveBlobAsFile(
                blob,
                "AfyaSmart_Appointments_Report.xlsx"
            );

        } catch (err) {

            console.error(
                "Excel report download failed:",
                err
            );

            setError(
                "Unable to generate the Excel report. Please try again."
            );

        } finally {

            setDownloading(null);
        }
    };


    return (

        <div
            style={{
                padding: "32px",
                backgroundColor: "#f8fafc",
                minHeight: "100vh"
            }}
        >

            {/* ==================================================
                PAGE HEADER
            ================================================== */}

            <div
                style={{
                    marginBottom: "30px"
                }}
            >

                <div
                    style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "12px",
                        marginBottom: "8px"
                    }}
                >

                    <BarChart3
                        size={30}
                        strokeWidth={2}
                    />

                    <h1
                        style={{
                            margin: 0,
                            fontSize: "28px",
                            fontWeight: "700",
                            color: "#0f172a"
                        }}
                    >
                        Report Center
                    </h1>

                </div>


                <p
                    style={{
                        margin: 0,
                        color: "#64748b",
                        fontSize: "15px"
                    }}
                >
                    Generate and download AfyaSmart system reports.
                </p>

            </div>


            {/* ==================================================
                ERROR MESSAGE
            ================================================== */}

            {error && (

                <div
                    style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "10px",
                        padding: "14px 18px",
                        marginBottom: "24px",
                        borderRadius: "10px",
                        backgroundColor: "#fef2f2",
                        border: "1px solid #fecaca",
                        color: "#b91c1c"
                    }}
                >

                    <span>
                        {error}
                    </span>

                </div>

            )}


            {/* ==================================================
                REPORT INFORMATION
            ================================================== */}

            <div
                style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "12px",
                    padding: "18px 20px",
                    marginBottom: "24px",
                    backgroundColor: "#ffffff",
                    border: "1px solid #e2e8f0",
                    borderRadius: "12px"
                }}
            >

                <CalendarDays
                    size={22}
                />

                <div>

                    <div
                        style={{
                            fontWeight: "600",
                            color: "#0f172a"
                        }}
                    >
                        Appointment Reports
                    </div>

                    <div
                        style={{
                            fontSize: "14px",
                            color: "#64748b",
                            marginTop: "3px"
                        }}
                    >
                        Generate a complete report of AfyaSmart
                        appointments.
                    </div>

                </div>

            </div>


            {/* ==================================================
                REPORT CARDS
            ================================================== */}

            <div
                style={{
                    display: "grid",
                    gridTemplateColumns:
                        "repeat(auto-fit, minmax(300px, 1fr))",
                    gap: "24px"
                }}
            >

                {/* ==================================================
                    PDF REPORT
                ================================================== */}

                <div
                    style={{
                        backgroundColor: "#ffffff",
                        border: "1px solid #e2e8f0",
                        borderRadius: "16px",
                        padding: "26px",
                        boxShadow:
                            "0 4px 12px rgba(15, 23, 42, 0.05)"
                    }}
                >

                    <div
                        style={{
                            display: "flex",
                            justifyContent: "space-between",
                            alignItems: "flex-start",
                            marginBottom: "22px"
                        }}
                    >

                        <div
                            style={{
                                width: "52px",
                                height: "52px",
                                borderRadius: "12px",
                                display: "flex",
                                alignItems: "center",
                                justifyContent: "center",
                                backgroundColor: "#fee2e2"
                            }}
                        >

                            <FileText
                                size={26}
                            />

                        </div>


                        <CheckCircle
                            size={21}
                        />

                    </div>


                    <h2
                        style={{
                            margin: "0 0 8px",
                            fontSize: "20px",
                            color: "#0f172a"
                        }}
                    >
                        Appointment PDF
                    </h2>


                    <p
                        style={{
                            margin: "0 0 24px",
                            color: "#64748b",
                            lineHeight: "1.6",
                            fontSize: "14px"
                        }}
                    >
                        Generate a printable PDF containing
                        appointment information, patients,
                        doctors, dates, times and statuses.
                    </p>


                    <button
                        onClick={handleDownloadPdf}
                        disabled={downloading !== null}
                        style={{
                            width: "100%",
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "center",
                            gap: "9px",
                            padding: "12px 18px",
                            border: "none",
                            borderRadius: "9px",
                            cursor:
                                downloading !== null
                                    ? "not-allowed"
                                    : "pointer",
                            backgroundColor: "#0f172a",
                            color: "#ffffff",
                            fontWeight: "600",
                            fontSize: "14px",
                            opacity:
                                downloading !== null
                                    ? 0.7
                                    : 1
                        }}
                    >

                        {downloading === "pdf" ? (

                            <>
                                <Loader2
                                    size={18}
                                    className="spin"
                                />

                                Generating PDF...
                            </>

                        ) : (

                            <>
                                <Download
                                    size={18}
                                />

                                Download PDF
                            </>

                        )}

                    </button>

                </div>


                {/* ==================================================
                    EXCEL REPORT
                ================================================== */}

                <div
                    style={{
                        backgroundColor: "#ffffff",
                        border: "1px solid #e2e8f0",
                        borderRadius: "16px",
                        padding: "26px",
                        boxShadow:
                            "0 4px 12px rgba(15, 23, 42, 0.05)"
                    }}
                >

                    <div
                        style={{
                            display: "flex",
                            justifyContent: "space-between",
                            alignItems: "flex-start",
                            marginBottom: "22px"
                        }}
                    >

                        <div
                            style={{
                                width: "52px",
                                height: "52px",
                                borderRadius: "12px",
                                display: "flex",
                                alignItems: "center",
                                justifyContent: "center",
                                backgroundColor: "#dcfce7"
                            }}
                        >

                            <FileSpreadsheet
                                size={26}
                            />

                        </div>


                        <CheckCircle
                            size={21}
                        />

                    </div>


                    <h2
                        style={{
                            margin: "0 0 8px",
                            fontSize: "20px",
                            color: "#0f172a"
                        }}
                    >
                        Appointment Excel
                    </h2>


                    <p
                        style={{
                            margin: "0 0 24px",
                            color: "#64748b",
                            lineHeight: "1.6",
                            fontSize: "14px"
                        }}
                    >
                        Generate an Excel spreadsheet containing
                        detailed appointment information for
                        analysis and record keeping.
                    </p>


                    <button
                        onClick={handleDownloadExcel}
                        disabled={downloading !== null}
                        style={{
                            width: "100%",
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "center",
                            gap: "9px",
                            padding: "12px 18px",
                            border: "none",
                            borderRadius: "9px",
                            cursor:
                                downloading !== null
                                    ? "not-allowed"
                                    : "pointer",
                            backgroundColor: "#0f172a",
                            color: "#ffffff",
                            fontWeight: "600",
                            fontSize: "14px",
                            opacity:
                                downloading !== null
                                    ? 0.7
                                    : 1
                        }}
                    >

                        {downloading === "excel" ? (

                            <>
                                <Loader2
                                    size={18}
                                    className="spin"
                                />

                                Generating Excel...
                            </>

                        ) : (

                            <>
                                <Download
                                    size={18}
                                />

                                Download Excel
                            </>

                        )}

                    </button>

                </div>

            </div>

        </div>
    );
};


export default AdminReports;